-- DROP (테스트 테이블)
DROP TABLE TB_TEST_01;

-- CREATE TABLE (테스트 테이블)
CREATE TABLE TB_TEST_01
( TEST_ID NUMBER(10) NOT NULL,
  TEST_NM VARCHAR2(50) NOT NULL,
  TEST_CONTENT VARCHAR2(200),
  CONSTRAINT TB_TEST_01 PRIMARY KEY (TEST_ID)
);

-- INSERT (테스트 테이블)
INSERT INTO TB_TEST_01 VALUES(1 , 'NM001' , 'CONTENT01');
INSERT INTO TB_TEST_01 VALUES(2 , 'NM002' , 'CONTENT02');
INSERT INTO TB_TEST_01 VALUES(3 , 'NM003' , 'CONTENT03');
INSERT INTO TB_TEST_01 VALUES(4 , 'NM004' , 'CONTENT04');
INSERT INTO TB_TEST_01 VALUES(5 , 'NM005' , 'CONTENT05');


-- DROP (이미지 게시판 파일)
DROP TABLE TB_IMG_BBS;

-- CREATE TABLE (이미지 게시판 파일)
CREATE TABLE TB_IMG_BBS
(
	IDX 		NUMBER(20) NOT NULL,
	SUBJECT 	VARCHAR2(100) NOT NULL,
	WRITER 		VARCHAR2(10) NOT NULL,
	CONTENT		VARCHAR2(3000) NOT NULL,
	REG_TS		TIMESTAMP DEFAULT SYSTIMESTAMP,
	MOD_TS		TIMESTAMP DEFAULT SYSTIMESTAMP,
	HIT			NUMBER(20) DEFAULT 0,
	IP			VARCHAR2(20) NOT NULL,
	CONSTRAINT TB_IMG_BBS_PK PRIMARY KEY(IDX)	
);

-- INSERT (이미지 게시판 파일)
INSERT INTO TB_IMG_BBS (IDX,SUBJECT,WRITER,CONTENT,IP) VALUES (01,'TEST_IMAGE01','iwkang01','test_image01','127.0.0.1');
INSERT INTO TB_IMG_BBS (IDX,SUBJECT,WRITER,CONTENT,IP) VALUES (02,'TEST_IMAGE02','iwkang02','test_image02','127.0.0.2');
INSERT INTO TB_IMG_BBS (IDX,SUBJECT,WRITER,CONTENT,IP) VALUES (03,'TEST_IMAGE03','iwkang03','test_image03','127.0.0.3');
INSERT INTO TB_IMG_BBS (IDX,SUBJECT,WRITER,CONTENT,IP) VALUES (04,'TEST_IMAGE04','iwkang04','test_image04','127.0.0.4');
INSERT INTO TB_IMG_BBS (IDX,SUBJECT,WRITER,CONTENT,IP) VALUES (05,'TEST_IMAGE05','iwkang05','test_image05','127.0.0.5');


-- DROP (이미지 게시판 파일)
DROP TABLE TB_IMG_BBS_FILE;

-- CREATE TABLE (이미지 게시판 파일)
CREATE TABLE TB_IMG_BBS_FILE
(
	FILE_IDX		NUMBER(20) NOT NULL,
	IDX				NUMBER(20) NOT NULL,
	REG_DT			DATE DEFAULT SYSDATE,
	FILE_SIZE		NUMBER(30) NOT NULL,
	FILE_NM			VARCHAR2(300) NOT NULL,
	FILE_TYPE		VARCHAR2(20) NOT NULL,
	TEMP_FILE_NM	VARCHAR2(300) NOT NULL,
	DELETE_YN		CHAR(1) DEFAULT 'N',
	CONSTRAINT TB_IMG_BBS_FILE_PK PRIMARY KEY(FILE_IDX),
	CONSTRAINT TM_IMG_BBS_FILE_FK FOREIGN KEY(IDX) REFERENCES TB_IMG_BBS(IDX) ON DELETE CASCADE
);

-- INSERT (이미지 게시판 파일)
INSERT INTO TB_IMG_BBS_FILE (FILE_IDX,IDX,FILE_SIZE,FILE_NM,FILE_TYPE,TEMP_FILE_NM) VALUES (01,01,'1024','test01.gif','gif','temp_test01.gif');
INSERT INTO TB_IMG_BBS_FILE (FILE_IDX,IDX,FILE_SIZE,FILE_NM,FILE_TYPE,TEMP_FILE_NM) VALUES (02,02,'1024','test02.gif','gif','temp_test02.gif');
INSERT INTO TB_IMG_BBS_FILE (FILE_IDX,IDX,FILE_SIZE,FILE_NM,FILE_TYPE,TEMP_FILE_NM) VALUES (03,03,'1024','test03.gif','gif','temp_test03.gif');
INSERT INTO TB_IMG_BBS_FILE (FILE_IDX,IDX,FILE_SIZE,FILE_NM,FILE_TYPE,TEMP_FILE_NM) VALUES (04,04,'1024','test04.gif','gif','temp_test04.gif');
INSERT INTO TB_IMG_BBS_FILE (FILE_IDX,IDX,FILE_SIZE,FILE_NM,FILE_TYPE,TEMP_FILE_NM) VALUES (05,05,'1024','test05.gif','gif','temp_test05.gif');
