/*
 * TABLE SCRIPT
 * 
 * 생성 : TB_ 테이블네임 
 * 
 */

-- CREATE TABLE
CREATE TABLE TB_USER
( 
	SEQ NUMBER NOT NULL,
	USER_ID VARCHAR2(10) NOT NULL,
	USER_NM VARCHAR2(50) NOT NULL,
	USER_PASSWORD VARCHAR2(50) NOT NULL,
	USER_PHONE VARCHAR2(100),
	USER_EMAIL VARCHAR2(100),
	ROLL_CD VARCHAR2(20) DEFAULT 'ROLL_001',
	CREATE_DT DATE DEFAULT SYSDATE,
	UPDATE_DT DATE DEFAULT SYSDATE,
	DELETE_YN VARCHAR2(1) DEFAULT 'N'
  CONSTRAINT TB_USER PRIMARY KEY (USER_ID)
);

-- INSERT
INSERT INTO TB_TEST_01 VALUES(1 , 'NM001' , 'CONTENT01');
INSERT INTO TB_TEST_01 VALUES(2 , 'NM002' , 'CONTENT02');
INSERT INTO TB_TEST_01 VALUES(3 , 'NM003' , 'CONTENT03');
INSERT INTO TB_TEST_01 VALUES(4 , 'NM004' , 'CONTENT04');
INSERT INTO TB_TEST_01 VALUES(5 , 'NM005' , 'CONTENT05');