/*
 * TABLE SCRIPT
 * 
 * 생성 : TB_ 테이블네임 
 * 
 */

-- CREATE TABLE (유저 관리)
CREATE TABLE TB_USER
( 
	SEQ NUMBER NOT NULL,
	USER_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
	USER_NM VARCHAR2(50) NOT NULL,
	USER_PASSWORD VARCHAR2(50) NOT NULL,
	USER_PHONE VARCHAR2(100),
	USER_EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	ROLL_CD VARCHAR2(20) DEFAULT 'ROLL_001',
	CREATE_DT DATE DEFAULT SYSDATE,
	UPDATE_DT DATE DEFAULT SYSDATE,
	DELETE_YN VARCHAR2(1) DEFAULT 'N'
);

-- INSERT (유저 관리)
INSERT INTO TB_USER VALUES(SQ_USER_01.NEXTVAL , 'single' , '싱글' , 'single' , '010-5132-0000' , 'souler2585@gmail.com', 'ROLL_000' , SYSDATE , SYSDATE , 'Y');
INSERT INTO TB_USER VALUES(SQ_USER_01.NEXTVAL , 'single2' , '싱글' , 'single' , '010-5132-0000' , '2222@gmail.com', 'ROLL_001' , SYSDATE , SYSDATE , 'Y');
INSERT INTO TB_USER VALUES(SQ_USER_01.NEXTVAL , 'single3' , '싱글' , 'single' , '010-5132-0000' , '3333@gmail.com', 'ROLL_001' , SYSDATE , SYSDATE , 'Y')


-- CREATE TABLE (이미지 게시판 글)
CREATE TABLE TB_IMG_BBS
(
	IDX 		NUMBER(20) NOT NULL,
	SUBJECT 	VARCHAR2(100) NOT NULL,
	WRITER 		VARCHAR2(10) NOT NULL,
	CONTENT		VARCHAR2(3000) NOT NULL,
	REG_TS		TIMESTAMP DEFAULT SYSTIMESTAMP,
	MOD_TS		TIMESTAMP DEFAULT SYSTIMESTAMP,
	HIT			NUMBER(20) DEFAULT 0,
	IP			VARCHAR2(20) NOT NULL,
	CONSTRAINT TB_IMG_BBS_PK PRIMARY KEY(IDX)	
);

-- INSERT (이미지 게시판 글)


-- CREATE TABLE (이미지 게시판 파일)
CREATE TABLE TB_IMG_BBS_FILE
(
	FILE_IDX		NUMBER(20) NOT NULL,
	IDX				NUMBER(20) NOT NULL,
	REG_DT			DATE DEFAULT SYSDATE,
	FILE_SIZE		NUMBER(30) NOT NULL,
	FILE_NM			VARCHAR2(300) NOT NULL,
	FILE_TYPE		VARCHAR2(20) NOT NULL,
	TEMP_FILE_NM	VARCHAR2(300) NOT NULL,
	DELETE_YN		CHAR(1) DEFAULT 'N',
	CONSTRAINT TB_IMG_BBS_FILE_PK PRIMARY KEY(FILE_IDX),
	CONSTRAINT TM_IMG_BBS_FILE_FK FOREIGN KEY(IDX) REFERENCES TB_IMG_BBS(IDX)
);

-- INSERT (이미지 게시판 파일)
